name: CI - Tests
on: 
  push:
    branches-ignore:
        - 'main'
        - 'releases/**'
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3.4.0
      with:
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run Tests                  
      run: ./gradlew test
    - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results        
          path: test-reports/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          fail-on-error: true  