name: CI - Tests
on: 
  push:
    branches-ignore:
        - 'main'
        - 'releases/**'
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run Tests                  
      run: ./gradlew test
    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: java-junit.xml
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: java Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit             # Format of test results    